/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author João Pedro
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        CodigoT = new javax.swing.JLabel();
        NomeT = new javax.swing.JLabel();
        TipoT = new javax.swing.JLabel();
        DescricaoT = new javax.swing.JLabel();
        ValorT = new javax.swing.JLabel();
        CodigoText = new javax.swing.JTextField();
        NomeText = new javax.swing.JTextField();
        TipoText = new javax.swing.JTextField();
        ValorText = new javax.swing.JTextField();
        DescricaoTextB = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        Sombra = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Cadastro de Seguro");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        CodigoT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CodigoT.setForeground(new java.awt.Color(255, 255, 255));
        CodigoT.setText("Código do Seguro:");
        getContentPane().add(CodigoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        NomeT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NomeT.setForeground(new java.awt.Color(255, 255, 255));
        NomeT.setText("Seguradora:");
        getContentPane().add(NomeT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        TipoT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TipoT.setForeground(new java.awt.Color(255, 255, 255));
        TipoT.setText("Tipo de Seguro:");
        getContentPane().add(TipoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        DescricaoT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DescricaoT.setForeground(new java.awt.Color(255, 255, 255));
        DescricaoT.setText("Descrição");
        getContentPane().add(DescricaoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        ValorT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ValorT.setForeground(new java.awt.Color(255, 255, 255));
        ValorT.setText("Valor do Seguro:");
        getContentPane().add(ValorT, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        CodigoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoTextActionPerformed(evt);
            }
        });
        getContentPane().add(CodigoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 150, 30));
        getContentPane().add(NomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, 30));
        getContentPane().add(TipoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 170, 30));
        getContentPane().add(ValorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 150, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        DescricaoTextB.setViewportView(jTextArea1);

        getContentPane().add(DescricaoTextB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 620, 170));

        jButton1.setBackground(new java.awt.Color(102, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Cadastrar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 140, 30));

        Sombra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(Sombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 710, 550));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/logo2.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -140, -1, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CodigoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CodigoT;
    private javax.swing.JTextField CodigoText;
    private javax.swing.JLabel DescricaoT;
    private javax.swing.JScrollPane DescricaoTextB;
    private javax.swing.JLabel NomeT;
    private javax.swing.JTextField NomeText;
    private javax.swing.JLabel Sombra;
    private javax.swing.JLabel TipoT;
    private javax.swing.JTextField TipoText;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel ValorT;
    private javax.swing.JTextField ValorText;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
