/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author João Pedro
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        NomeT = new javax.swing.JLabel();
        CPFT = new javax.swing.JLabel();
        NacimentoT = new javax.swing.JLabel();
        Rg = new javax.swing.JLabel();
        EnderecoT = new javax.swing.JLabel();
        CEPT = new javax.swing.JLabel();
        EmailT = new javax.swing.JLabel();
        TelefoneT = new javax.swing.JLabel();
        NomeText = new javax.swing.JTextField();
        CPFText = new javax.swing.JTextField();
        NacimentoText = new javax.swing.JTextField();
        RgText = new javax.swing.JTextField();
        EnderecoText = new javax.swing.JTextField();
        CEPText = new javax.swing.JTextField();
        EmailText = new javax.swing.JTextField();
        TelefoneText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Sombra = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Cadastro de Cliente");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        NomeT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NomeT.setForeground(new java.awt.Color(255, 255, 255));
        NomeT.setText("Nome:");
        getContentPane().add(NomeT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        CPFT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CPFT.setForeground(new java.awt.Color(255, 255, 255));
        CPFT.setText("CPF:");
        getContentPane().add(CPFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        NacimentoT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NacimentoT.setForeground(new java.awt.Color(255, 255, 255));
        NacimentoT.setText("Data de Nacimento:");
        getContentPane().add(NacimentoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        Rg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rg.setForeground(new java.awt.Color(255, 255, 255));
        Rg.setText("RG:");
        getContentPane().add(Rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        EnderecoT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EnderecoT.setForeground(new java.awt.Color(255, 255, 255));
        EnderecoT.setText("Endereço:");
        getContentPane().add(EnderecoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        CEPT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CEPT.setForeground(new java.awt.Color(255, 255, 255));
        CEPT.setText("CEP:");
        getContentPane().add(CEPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, -1));

        EmailT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmailT.setForeground(new java.awt.Color(255, 255, 255));
        EmailT.setText("Email:");
        getContentPane().add(EmailT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        TelefoneT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TelefoneT.setForeground(new java.awt.Color(255, 255, 255));
        TelefoneT.setText("Telefone:");
        getContentPane().add(TelefoneT, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        NomeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeTextActionPerformed(evt);
            }
        });
        getContentPane().add(NomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 230, 30));
        getContentPane().add(CPFText, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 200, 30));
        getContentPane().add(NacimentoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 120, 30));

        RgText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RgTextActionPerformed(evt);
            }
        });
        getContentPane().add(RgText, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 200, 30));
        getContentPane().add(EnderecoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 340, 30));
        getContentPane().add(CEPText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 150, 30));
        getContentPane().add(EmailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 260, 30));
        getContentPane().add(TelefoneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 190, 30));

        jButton1.setBackground(new java.awt.Color(102, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Cadastrar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 140, 30));

        Sombra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(Sombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 710, 550));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/logo2.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -140, -1, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeTextActionPerformed

    private void RgTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RgTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RgTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CEPT;
    private javax.swing.JTextField CEPText;
    private javax.swing.JLabel CPFT;
    private javax.swing.JTextField CPFText;
    private javax.swing.JLabel EmailT;
    private javax.swing.JTextField EmailText;
    private javax.swing.JLabel EnderecoT;
    private javax.swing.JTextField EnderecoText;
    private javax.swing.JLabel NacimentoT;
    private javax.swing.JTextField NacimentoText;
    private javax.swing.JLabel NomeT;
    private javax.swing.JTextField NomeText;
    private javax.swing.JLabel Rg;
    private javax.swing.JTextField RgText;
    private javax.swing.JLabel Sombra;
    private javax.swing.JLabel TelefoneT;
    private javax.swing.JTextField TelefoneText;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
