/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author João Pedro
 */
public class CadastroImovel extends javax.swing.JFrame {

    /**
     * Creates new form CadastroImovel
     */
    public CadastroImovel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        EnderecoT = new javax.swing.JLabel();
        DataCT = new javax.swing.JLabel();
        AreaT = new javax.swing.JLabel();
        AreaCT = new javax.swing.JLabel();
        DormitorioT = new javax.swing.JLabel();
        BanheiroT = new javax.swing.JLabel();
        VGaragemT = new javax.swing.JLabel();
        VIPTUT = new javax.swing.JLabel();
        VVenda = new javax.swing.JLabel();
        VAluguel = new javax.swing.JLabel();
        ImovelT = new javax.swing.JLabel();
        ApartamentoT = new javax.swing.JLabel();
        ComercialT = new javax.swing.JLabel();
        AndarT = new javax.swing.JLabel();
        VCondominioT = new javax.swing.JLabel();
        ImpostoT = new javax.swing.JLabel();
        EnderecoText = new javax.swing.JTextField();
        DataCText = new javax.swing.JTextField();
        AreaText = new javax.swing.JTextField();
        AreaCText = new javax.swing.JTextField();
        DormitorioText = new javax.swing.JTextField();
        BanheiroText = new javax.swing.JTextField();
        VGaragemText = new javax.swing.JTextField();
        VIPTUText = new javax.swing.JTextField();
        VVendaText = new javax.swing.JTextField();
        VAluguelText = new javax.swing.JTextField();
        AndarText = new javax.swing.JTextField();
        VCondomioText = new javax.swing.JTextField();
        ImpostoText = new javax.swing.JTextField();
        ImovelBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 51, 51));
        Titulo.setText("Cadastro de Imóvel");

        EnderecoT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EnderecoT.setForeground(new java.awt.Color(0, 0, 0));
        EnderecoT.setText("Endereço:");

        DataCT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DataCT.setForeground(new java.awt.Color(0, 0, 0));
        DataCT.setText("Data de Construção:");

        AreaT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AreaT.setForeground(new java.awt.Color(0, 0, 0));
        AreaT.setText("Área Total:");

        AreaCT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AreaCT.setForeground(new java.awt.Color(0, 0, 0));
        AreaCT.setText("Área Construida:");

        DormitorioT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DormitorioT.setForeground(new java.awt.Color(0, 0, 0));
        DormitorioT.setText("nº de Dormitórios:");

        BanheiroT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BanheiroT.setForeground(new java.awt.Color(0, 0, 0));
        BanheiroT.setText("nº de Banheiros:");

        VGaragemT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        VGaragemT.setForeground(new java.awt.Color(0, 0, 0));
        VGaragemT.setText("nº de Vagas na Garagem:");

        VIPTUT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        VIPTUT.setForeground(new java.awt.Color(0, 0, 0));
        VIPTUT.setText("Valor do IPTU:");

        VVenda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        VVenda.setForeground(new java.awt.Color(0, 0, 0));
        VVenda.setText("Valor da Venda:");

        VAluguel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        VAluguel.setForeground(new java.awt.Color(0, 0, 0));
        VAluguel.setText("Valor do Aluguel:");

        ImovelT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ImovelT.setForeground(new java.awt.Color(0, 0, 0));
        ImovelT.setText("Tipo de Imóvel:");

        ApartamentoT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ApartamentoT.setForeground(new java.awt.Color(0, 51, 51));
        ApartamentoT.setText("Apartamento Residencial");

        ComercialT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ComercialT.setForeground(new java.awt.Color(0, 51, 51));
        ComercialT.setText("Comercial");

        AndarT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AndarT.setForeground(new java.awt.Color(0, 0, 0));
        AndarT.setText("Andar:");

        VCondominioT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        VCondominioT.setForeground(new java.awt.Color(0, 0, 0));
        VCondominioT.setText("Valor do Condomínio:");

        ImpostoT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ImpostoT.setForeground(new java.awt.Color(0, 0, 0));
        ImpostoT.setText("Taxa de Imposto:");

        DataCText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataCTextActionPerformed(evt);
            }
        });

        DormitorioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DormitorioTextActionPerformed(evt);
            }
        });

        VAluguelText.setToolTipText("");

        ImovelBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ImovelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa Residencial", "Apartamento Residencial", "Comercial" }));

        jButton1.setBackground(new java.awt.Color(102, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Cadastrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(180, 180, 180)
                            .addComponent(Titulo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(470, 470, 470)
                            .addComponent(DataCT))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(EnderecoT)
                            .addGap(3, 3, 3)
                            .addComponent(EnderecoText, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(DataCText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(AreaT)
                            .addGap(6, 6, 6)
                            .addComponent(AreaText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(160, 160, 160)
                            .addComponent(AreaCT)
                            .addGap(9, 9, 9)
                            .addComponent(AreaCText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(DormitorioT)
                            .addGap(12, 12, 12)
                            .addComponent(DormitorioText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(180, 180, 180)
                            .addComponent(VIPTUT)
                            .addGap(17, 17, 17)
                            .addComponent(VIPTUText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(VGaragemT)
                            .addGap(9, 9, 9)
                            .addComponent(VGaragemText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(120, 120, 120)
                            .addComponent(VVenda)
                            .addGap(15, 15, 15)
                            .addComponent(VVendaText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BanheiroT)
                            .addGap(11, 11, 11)
                            .addComponent(BanheiroText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(180, 180, 180)
                            .addComponent(VAluguel)
                            .addGap(13, 13, 13)
                            .addComponent(VAluguelText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ImovelT)
                            .addGap(17, 17, 17)
                            .addComponent(ImovelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ApartamentoT)
                            .addGap(285, 285, 285)
                            .addComponent(ComercialT))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(AndarT)
                            .addGap(8, 8, 8)
                            .addComponent(AndarText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(280, 280, 280)
                            .addComponent(ImpostoT)
                            .addGap(13, 13, 13)
                            .addComponent(ImpostoText, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(VCondominioT)
                            .addGap(14, 14, 14)
                            .addComponent(VCondomioText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(500, 500, 500)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(Titulo)
                    .addGap(2, 2, 2)
                    .addComponent(DataCT)
                    .addGap(5, 5, 5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EnderecoT)
                        .addComponent(EnderecoText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DataCText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AreaT)
                        .addComponent(AreaText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AreaCT)
                        .addComponent(AreaCText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DormitorioT)
                        .addComponent(DormitorioText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(VIPTUT)
                        .addComponent(VIPTUText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(VGaragemT)
                        .addComponent(VGaragemText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(VVenda)
                        .addComponent(VVendaText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BanheiroT)
                        .addComponent(BanheiroText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(VAluguel)
                        .addComponent(VAluguelText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ImovelT)
                        .addComponent(ImovelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ApartamentoT)
                        .addComponent(ComercialT))
                    .addGap(8, 8, 8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AndarT)
                        .addComponent(AndarText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ImpostoT)
                        .addComponent(ImpostoText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(VCondominioT)
                        .addComponent(VCondomioText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DataCTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataCTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataCTextActionPerformed

    private void DormitorioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DormitorioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DormitorioTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroImovel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AndarT;
    private javax.swing.JTextField AndarText;
    private javax.swing.JLabel ApartamentoT;
    private javax.swing.JLabel AreaCT;
    private javax.swing.JTextField AreaCText;
    private javax.swing.JLabel AreaT;
    private javax.swing.JTextField AreaText;
    private javax.swing.JLabel BanheiroT;
    private javax.swing.JTextField BanheiroText;
    private javax.swing.JLabel ComercialT;
    private javax.swing.JLabel DataCT;
    private javax.swing.JTextField DataCText;
    private javax.swing.JLabel DormitorioT;
    private javax.swing.JTextField DormitorioText;
    private javax.swing.JLabel EnderecoT;
    private javax.swing.JTextField EnderecoText;
    private javax.swing.JComboBox<String> ImovelBox;
    private javax.swing.JLabel ImovelT;
    private javax.swing.JLabel ImpostoT;
    private javax.swing.JTextField ImpostoText;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel VAluguel;
    private javax.swing.JTextField VAluguelText;
    private javax.swing.JLabel VCondominioT;
    private javax.swing.JTextField VCondomioText;
    private javax.swing.JLabel VGaragemT;
    private javax.swing.JTextField VGaragemText;
    private javax.swing.JLabel VIPTUT;
    private javax.swing.JTextField VIPTUText;
    private javax.swing.JLabel VVenda;
    private javax.swing.JTextField VVendaText;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
