/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.CadastroCorretorController;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author João Pedro
 */
public class CadastroCorretor extends javax.swing.JFrame {

    private final CadastroCorretorController controller;

    /**
     * Creates new form CadastroCorretor
     */
    public CadastroCorretor() {
        initComponents();
        controller = new CadastroCorretorController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        NomeT = new javax.swing.JLabel();
        CPFT = new javax.swing.JLabel();
        NacimentoT = new javax.swing.JLabel();
        Rg = new javax.swing.JLabel();
        EnderecoT = new javax.swing.JLabel();
        CEPT = new javax.swing.JLabel();
        EmailT = new javax.swing.JLabel();
        TelefoneT = new javax.swing.JLabel();
        SalarioT = new javax.swing.JLabel();
        DataT = new javax.swing.JLabel();
        CreciT = new javax.swing.JLabel();
        PisT = new javax.swing.JLabel();
        NomeText = new javax.swing.JTextField();
        CPFText = new javax.swing.JTextField();
        NacimentoText = new javax.swing.JTextField();
        RgText = new javax.swing.JTextField();
        EnderecoText = new javax.swing.JTextField();
        CEPText = new javax.swing.JTextField();
        EmailText = new javax.swing.JTextField();
        TelefoneText = new javax.swing.JTextField();
        SalarioText = new javax.swing.JTextField();
        DataText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        CreciText = new javax.swing.JTextField();
        PisText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 51, 51));
        Titulo.setText("Cadastro de Corretor");

        NomeT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NomeT.setForeground(new java.awt.Color(0, 0, 0));
        NomeT.setText("Nome:");

        CPFT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CPFT.setForeground(new java.awt.Color(0, 0, 0));
        CPFT.setText("CPF:");

        NacimentoT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NacimentoT.setForeground(new java.awt.Color(0, 0, 0));
        NacimentoT.setText("Data de Nacimento:");

        Rg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rg.setForeground(new java.awt.Color(0, 0, 0));
        Rg.setText("RG:");

        EnderecoT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EnderecoT.setForeground(new java.awt.Color(0, 0, 0));
        EnderecoT.setText("Endereço:");

        CEPT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CEPT.setForeground(new java.awt.Color(0, 0, 0));
        CEPT.setText("CEP:");

        EmailT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmailT.setForeground(new java.awt.Color(0, 0, 0));
        EmailT.setText("Email:");

        TelefoneT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TelefoneT.setForeground(new java.awt.Color(0, 0, 0));
        TelefoneT.setText("Telefone:");

        SalarioT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SalarioT.setForeground(new java.awt.Color(0, 0, 0));
        SalarioT.setText("Salário do funcionário");

        DataT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DataT.setForeground(new java.awt.Color(0, 0, 0));
        DataT.setText("Data de Admissão");

        CreciT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreciT.setForeground(new java.awt.Color(0, 0, 0));
        CreciT.setText("Creci:");

        PisT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PisT.setForeground(new java.awt.Color(0, 0, 0));
        PisT.setText("Pis:");

        NomeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeTextActionPerformed(evt);
            }
        });

        RgText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RgTextActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(SalarioT)
                                    .addGap(6, 6, 6)
                                    .addComponent(SalarioText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(DataT)
                                    .addGap(4, 4, 4)
                                    .addComponent(DataText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(490, 490, 490)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(EnderecoT)
                                    .addGap(13, 13, 13)
                                    .addComponent(EnderecoText, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(CEPT)
                                    .addGap(6, 6, 6)
                                    .addComponent(CEPText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(EmailT)
                                        .addComponent(CreciT))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CreciText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(10, 10, 10)
                                    .addComponent(TelefoneT)
                                    .addGap(9, 9, 9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TelefoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(PisT)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(PisText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(NomeT)
                                    .addGap(7, 7, 7)
                                    .addComponent(NomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(90, 90, 90)
                                    .addComponent(CPFT)
                                    .addGap(16, 16, 16)
                                    .addComponent(CPFText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(NacimentoT)
                                    .addGap(13, 13, 13)
                                    .addComponent(NacimentoText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(90, 90, 90)
                                    .addComponent(Rg)
                                    .addGap(23, 23, 23)
                                    .addComponent(RgText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Titulo)
                        .addGap(174, 174, 174))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Titulo)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomeT)
                    .addComponent(NomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPFT)
                    .addComponent(CPFText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NacimentoT)
                    .addComponent(NacimentoText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rg)
                    .addComponent(RgText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnderecoT)
                    .addComponent(EnderecoText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CEPT)
                        .addComponent(CEPText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelefoneT)
                    .addComponent(TelefoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailT, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CreciText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CreciT))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PisText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PisT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SalarioT)
                    .addComponent(SalarioText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataT)
                    .addComponent(DataText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NomeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeTextActionPerformed

    private void RgTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RgTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RgTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        controller.cadastrarCorretor();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCorretor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CEPT;
    private javax.swing.JTextField CEPText;
    private javax.swing.JLabel CPFT;
    private javax.swing.JTextField CPFText;
    private javax.swing.JLabel CreciT;
    private javax.swing.JTextField CreciText;
    private javax.swing.JLabel DataT;
    private javax.swing.JTextField DataText;
    private javax.swing.JLabel EmailT;
    private javax.swing.JTextField EmailText;
    private javax.swing.JLabel EnderecoT;
    private javax.swing.JTextField EnderecoText;
    private javax.swing.JLabel NacimentoT;
    private javax.swing.JTextField NacimentoText;
    private javax.swing.JLabel NomeT;
    private javax.swing.JTextField NomeText;
    private javax.swing.JLabel PisT;
    private javax.swing.JTextField PisText;
    private javax.swing.JLabel Rg;
    private javax.swing.JTextField RgText;
    private javax.swing.JLabel SalarioT;
    private javax.swing.JTextField SalarioText;
    private javax.swing.JLabel TelefoneT;
    private javax.swing.JTextField TelefoneText;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    public JTextField getCEPText() {
        return CEPText;
    }

    public void setCEPText(JTextField CEPText) {
        this.CEPText = CEPText;
    }

    public JTextField getCPFText() {
        return CPFText;
    }

    public void setCPFText(JTextField CPFText) {
        this.CPFText = CPFText;
    }

    public JTextField getDataText() {
        return DataText;
    }

    public void setDataText(JTextField DataText) {
        this.DataText = DataText;
    }

    public JTextField getEmailText() {
        return EmailText;
    }

    public void setEmailText(JTextField EmailText) {
        this.EmailText = EmailText;
    }

    public JTextField getEnderecoText() {
        return EnderecoText;
    }

    public void setEnderecoText(JTextField EnderecoText) {
        this.EnderecoText = EnderecoText;
    }

    public JTextField getNacimentoText() {
        return NacimentoText;
    }

    public void setNacimentoText(JTextField NacimentoText) {
        this.NacimentoText = NacimentoText;
    }

    public JTextField getNomeText() {
        return NomeText;
    }

    public void setNomeText(JTextField NomeText) {
        this.NomeText = NomeText;
    }

    public JTextField getRgText() {
        return RgText;
    }

    public void setRgText(JTextField RgText) {
        this.RgText = RgText;
    }

    public JTextField getSalarioText() {
        return SalarioText;
    }

    public void setSalarioText(JTextField SalarioText) {
        this.SalarioText = SalarioText;
    }

    public JTextField getTelefoneText() {
        return TelefoneText;
    }

    public void setTelefoneText(JTextField TelefoneText) {
        this.TelefoneText = TelefoneText;
    }

    public JTextField getCreciText() {
        return CreciText;
    }

    public void setCreciText(JTextField CreciText) {
        this.CreciText = CreciText;
    }


    public JTextField getPisText() {
        return PisText;
    }

    public void setPisText(JTextField PisText) {
        this.PisText = PisText;
    }

    
    
    public void mensagem(String menssage){
        JOptionPane.showMessageDialog(null, menssage);
    }

}
