/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author João Pedro
 */
public class Informacoes extends javax.swing.JFrame {

    /**
     * Creates new form Informacoes
     */
    public Informacoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabelaInfo = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        NomeT = new javax.swing.JLabel();
        AlugueisT = new javax.swing.JLabel();
        MesRefT = new javax.swing.JLabel();
        ValortoT = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        AlugueisBox = new javax.swing.JComboBox<>();
        TipoImovel = new javax.swing.JComboBox<>();
        DisponivelBox = new javax.swing.JComboBox<>();
        MesRefBox = new javax.swing.JComboBox<>();
        ListaInfo = new javax.swing.JButton();
        ListaVend = new javax.swing.JButton();
        ValorTex = new javax.swing.JTextField();
        NomeTex = new javax.swing.JTextField();
        PretoBackgroud = new javax.swing.JLabel();
        TelaBackgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Tipo de imóvel", "Status", "Cliente", "Valor de IPTU", "Preço", "Data"
            }
        ));
        TabelaInfo.setViewportView(jTable1);

        getContentPane().add(TabelaInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 730, 290));

        NomeT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeT.setForeground(new java.awt.Color(255, 255, 255));
        NomeT.setText("Nome do cliente");
        getContentPane().add(NomeT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 110, 20));

        AlugueisT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AlugueisT.setForeground(new java.awt.Color(255, 255, 255));
        AlugueisT.setText("Alugueis");
        getContentPane().add(AlugueisT, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 70, 20));

        MesRefT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MesRefT.setForeground(new java.awt.Color(255, 255, 255));
        MesRefT.setText("mês referente");
        getContentPane().add(MesRefT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        ValortoT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ValortoT.setForeground(new java.awt.Color(255, 255, 255));
        ValortoT.setText("Valor Total");
        getContentPane().add(ValortoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, -1, -1));

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Imóveis");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        AlugueisBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Finalizados", "em vigência" }));
        getContentPane().add(AlugueisBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 100, 20));

        TipoImovel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TipoImovel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Imoveis", "Casa Residencial", "Apartamento Residencial", "Comercial" }));
        getContentPane().add(TipoImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 190, 20));

        DisponivelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponiveis", "Indisponiveis", "Pagamento Atrasado" }));
        getContentPane().add(DisponivelBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 150, -1));

        MesRefBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MesRefBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        getContentPane().add(MesRefBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 150, 20));

        ListaInfo.setBackground(new java.awt.Color(102, 255, 204));
        ListaInfo.setText("Listar informações");
        getContentPane().add(ListaInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

        ListaVend.setBackground(new java.awt.Color(102, 255, 204));
        ListaVend.setText("Listar vendas");
        getContentPane().add(ListaVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, 20));

        ValorTex.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ValorTex.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ValorTex, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 460, 110, 20));
        getContentPane().add(NomeTex, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 190, -1));

        PretoBackgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(PretoBackgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 800, 460));

        TelaBackgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/MenuBack.jpeg"))); // NOI18N
        getContentPane().add(TelaBackgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AlugueisBox;
    private javax.swing.JLabel AlugueisT;
    private javax.swing.JComboBox<String> DisponivelBox;
    private javax.swing.JButton ListaInfo;
    private javax.swing.JButton ListaVend;
    private javax.swing.JComboBox<String> MesRefBox;
    private javax.swing.JLabel MesRefT;
    private javax.swing.JLabel NomeT;
    private javax.swing.JTextField NomeTex;
    private javax.swing.JLabel PretoBackgroud;
    private javax.swing.JScrollPane TabelaInfo;
    private javax.swing.JLabel TelaBackgroud;
    private javax.swing.JComboBox<String> TipoImovel;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField ValorTex;
    private javax.swing.JLabel ValortoT;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
