/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author João Pedro
 */
public class InformaçõesClientes extends javax.swing.JFrame {

    /**
     * Creates new form InformaçõesClientes
     */
    public InformaçõesClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        NomeT = new javax.swing.JLabel();
        AlugueisT = new javax.swing.JLabel();
        HistoricoB = new javax.swing.JButton();
        AlugueisB = new javax.swing.JButton();
        NomeText = new javax.swing.JTextField();
        AlugueisBox = new javax.swing.JComboBox<>();
        Tabela = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PretoBackground = new javax.swing.JLabel();
        TelaBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Clientes");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        NomeT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeT.setForeground(new java.awt.Color(255, 255, 255));
        NomeT.setText("Nome do cliente");
        getContentPane().add(NomeT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        AlugueisT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AlugueisT.setForeground(new java.awt.Color(255, 255, 255));
        AlugueisT.setText("Alugueis");
        getContentPane().add(AlugueisT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 60, 20));

        HistoricoB.setBackground(new java.awt.Color(102, 255, 204));
        HistoricoB.setText("Ver Histórico");
        getContentPane().add(HistoricoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 110, 20));

        AlugueisB.setBackground(new java.awt.Color(102, 255, 204));
        AlugueisB.setText("Visualizar");
        getContentPane().add(AlugueisB, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 110, -1));
        getContentPane().add(NomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 190, -1));

        AlugueisBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Atrasados" }));
        getContentPane().add(AlugueisBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 110, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Email", "Código do Imóvel", "Status", "Valor"
            }
        ));
        Tabela.setViewportView(jTable1);

        getContentPane().add(Tabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 187, 710, 280));

        PretoBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(PretoBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 20, 790, 480));

        TelaBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/MenuBack.jpeg"))); // NOI18N
        getContentPane().add(TelaBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformaçõesClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformaçõesClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformaçõesClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformaçõesClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformaçõesClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlugueisB;
    private javax.swing.JComboBox<String> AlugueisBox;
    private javax.swing.JLabel AlugueisT;
    private javax.swing.JButton HistoricoB;
    private javax.swing.JLabel NomeT;
    private javax.swing.JTextField NomeText;
    private javax.swing.JLabel PretoBackground;
    private javax.swing.JScrollPane Tabela;
    private javax.swing.JLabel TelaBackground;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
