/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.InformacoesImoveisController;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author João Pedro
 */
public class InformacoesImoveis extends javax.swing.JFrame {

    private final InformacoesImoveisController controller;

    /**
     * Creates new form InformacoesImoveis
     */
    public InformacoesImoveis() {
        initComponents();
        controller = new InformacoesImoveisController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabelaInfo = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        NomeT = new javax.swing.JLabel();
        AlugueisT = new javax.swing.JLabel();
        MesRefT = new javax.swing.JLabel();
        ValortoT = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        AlugueisBox = new javax.swing.JComboBox<>();
        TipoImovel = new javax.swing.JComboBox<>();
        DisponivelBox = new javax.swing.JComboBox<>();
        MesRefBox = new javax.swing.JComboBox<>();
        ListaInfo = new javax.swing.JButton();
        ListaVend = new javax.swing.JButton();
        ValorTex = new javax.swing.JTextField();
        NomeTex = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Tipo de imóvel", "Status", "Cliente", "Valor de IPTU", "Preço", "Data"
            }
        ));
        TabelaInfo.setViewportView(jTable1);

        NomeT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeT.setForeground(new java.awt.Color(0, 0, 0));
        NomeT.setText("Nome do cliente");

        AlugueisT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AlugueisT.setForeground(new java.awt.Color(0, 0, 0));
        AlugueisT.setText("Alugueis");

        MesRefT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MesRefT.setForeground(new java.awt.Color(0, 0, 0));
        MesRefT.setText("mês referente");

        ValortoT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ValortoT.setForeground(new java.awt.Color(0, 0, 0));
        ValortoT.setText("Valor Total");

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 51, 51));
        Titulo.setText("Imóveis");

        AlugueisBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Finalizados", "em vigência" }));

        TipoImovel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TipoImovel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Imoveis", "Casa Residencial", "Apartamento Residencial", "Comercial" }));

        DisponivelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponiveis", "Indisponiveis", "Pagamento Atrasado" }));

        MesRefBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MesRefBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        ListaInfo.setBackground(new java.awt.Color(102, 255, 204));
        ListaInfo.setForeground(new java.awt.Color(0, 0, 0));
        ListaInfo.setText("Listar informações");

        ListaVend.setBackground(new java.awt.Color(102, 255, 204));
        ListaVend.setForeground(new java.awt.Color(0, 0, 0));
        ListaVend.setText("Listar vendas");

        ValorTex.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ValorTex.setForeground(new java.awt.Color(255, 255, 255));

        NomeTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeTexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(Titulo))
                    .addComponent(TabelaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MesRefT)
                        .addGap(16, 16, 16)
                        .addComponent(MesRefBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ListaVend)
                        .addGap(180, 180, 180)
                        .addComponent(ValortoT)
                        .addGap(15, 15, 15)
                        .addComponent(ValorTex, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(TipoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(DisponivelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(AlugueisT, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(AlugueisBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ListaInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NomeT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(NomeTex, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TipoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisponivelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlugueisT)
                    .addComponent(AlugueisBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListaInfo))
                .addGap(15, 15, 15)
                .addComponent(TabelaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MesRefT)
                    .addComponent(MesRefBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListaVend, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValortoT)
                    .addComponent(ValorTex, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeTexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacoesImoveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacoesImoveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacoesImoveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacoesImoveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacoesImoveis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AlugueisBox;
    private javax.swing.JLabel AlugueisT;
    private javax.swing.JComboBox<String> DisponivelBox;
    private javax.swing.JButton ListaInfo;
    private javax.swing.JButton ListaVend;
    private javax.swing.JComboBox<String> MesRefBox;
    private javax.swing.JLabel MesRefT;
    private javax.swing.JLabel NomeT;
    private javax.swing.JTextField NomeTex;
    private javax.swing.JScrollPane TabelaInfo;
    private javax.swing.JComboBox<String> TipoImovel;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField ValorTex;
    private javax.swing.JLabel ValortoT;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public String getAlugueisBox() {
        return AlugueisBox.getSelectedItem().toString();
    }

    public void setAlugueisBox(JComboBox<String> AlugueisBox) {
        this.AlugueisBox = AlugueisBox;
    }

    public String getDisponivelBox() {
        return DisponivelBox.getSelectedItem().toString();
    }

    public void setDisponivelBox(JComboBox<String> DisponivelBox) {
        this.DisponivelBox = DisponivelBox;
    }

    public String getMesRefBox() {
        return MesRefBox.getSelectedItem().toString();
    }

    public void setMesRefBox(JComboBox<String> MesRefBox) {
        this.MesRefBox = MesRefBox;
    }

    public JTextField getNomeTex() {
        return NomeTex;
    }

    public void setNomeTex(JTextField NomeTex) {
        this.NomeTex = NomeTex;
    }

    public String getTipoImovel() {
        return TipoImovel.getSelectedItem().toString();
    }

    public void setTipoImovel(JComboBox<String> TipoImovel) {
        this.TipoImovel = TipoImovel;
    }

    public JTextField getValorTex() {
        return ValorTex;
    }

    public void setValorTex(JTextField ValorTex) {
        this.ValorTex = ValorTex;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }



}
