/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author João Pedro
 */
public class InformacoesCorretores extends javax.swing.JFrame {

    /**
     * Creates new form InformacoesCorretores
     */
    public InformacoesCorretores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FuncionarioBox = new javax.swing.JComboBox<>();
        MesBox = new javax.swing.JComboBox<>();
        Tabela = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Titulo = new javax.swing.JLabel();
        MesT = new javax.swing.JLabel();
        PretoBackgroud = new javax.swing.JLabel();
        TelaBackgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FuncionarioBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "funcionário do mês" }));
        getContentPane().add(FuncionarioBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 170, -1));

        MesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        getContentPane().add(MesBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 160, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código ", "Nome", "CPF", "Email", "Salário", "Número de vendas"
            }
        ));
        Tabela.setViewportView(jTable1);

        getContentPane().add(Tabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 157, 690, 290));

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Corretores");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        MesT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MesT.setForeground(new java.awt.Color(255, 255, 255));
        MesT.setText("Mês de referencia");
        getContentPane().add(MesT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 110, 20));

        PretoBackgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(PretoBackgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 20, 790, 480));

        TelaBackgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/MenuBack.jpeg"))); // NOI18N
        getContentPane().add(TelaBackgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacoesCorretores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacoesCorretores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacoesCorretores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacoesCorretores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacoesCorretores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FuncionarioBox;
    private javax.swing.JComboBox<String> MesBox;
    private javax.swing.JLabel MesT;
    private javax.swing.JLabel PretoBackgroud;
    private javax.swing.JScrollPane Tabela;
    private javax.swing.JLabel TelaBackgroud;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
