/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author João Pedro
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backgroud = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastros = new javax.swing.JMenu();
        CadastroCliente = new javax.swing.JMenuItem();
        CadastroCorretor = new javax.swing.JMenuItem();
        CadastroImovel = new javax.swing.JMenuItem();
        CadastroSeguro = new javax.swing.JMenuItem();
        Operacoes = new javax.swing.JMenu();
        OperacaoAluguel = new javax.swing.JMenuItem();
        OperacaoVenda = new javax.swing.JMenuItem();
        Informacoes = new javax.swing.JMenu();
        Imoveis = new javax.swing.JMenuItem();
        Clientes = new javax.swing.JMenuItem();
        Corretores = new javax.swing.JMenuItem();
        Seguros = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/MenuBack.jpeg"))); // NOI18N

        jMenuBar1.setToolTipText("");

        Cadastros.setForeground(new java.awt.Color(255, 255, 255));
        Cadastros.setText("Cadastros");

        CadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icones/cliente-icon.png"))); // NOI18N
        CadastroCliente.setText("Cliente");
        CadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroClienteActionPerformed(evt);
            }
        });
        Cadastros.add(CadastroCliente);

        CadastroCorretor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icones/cliente-icon.png"))); // NOI18N
        CadastroCorretor.setText("Corretor");
        Cadastros.add(CadastroCorretor);

        CadastroImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icones/home-page.png"))); // NOI18N
        CadastroImovel.setText("Imovel");
        Cadastros.add(CadastroImovel);

        CadastroSeguro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icones/affirmative-check-mark.png"))); // NOI18N
        CadastroSeguro.setText("Seguro");
        Cadastros.add(CadastroSeguro);

        jMenuBar1.add(Cadastros);

        Operacoes.setText("Operações");

        OperacaoAluguel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icones/investment.png"))); // NOI18N
        OperacaoAluguel.setText("Alugueis");
        Operacoes.add(OperacaoAluguel);

        OperacaoVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icones/money-bag.png"))); // NOI18N
        OperacaoVenda.setText("Vendas");
        Operacoes.add(OperacaoVenda);

        jMenuBar1.add(Operacoes);

        Informacoes.setText("Informações");

        Imoveis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icones/home-page.png"))); // NOI18N
        Imoveis.setText("Imóveis");
        Imoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImoveisActionPerformed(evt);
            }
        });
        Informacoes.add(Imoveis);

        Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icones/cliente-icon.png"))); // NOI18N
        Clientes.setText("Clientes");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        Informacoes.add(Clientes);

        Corretores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icones/cliente-icon.png"))); // NOI18N
        Corretores.setText("Corretores");
        Informacoes.add(Corretores);

        Seguros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icones/relatorioTrabalho-icon.png"))); // NOI18N
        Seguros.setText("Seguros");
        Informacoes.add(Seguros);

        jMenuBar1.add(Informacoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgroud)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Backgroud)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImoveisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImoveisActionPerformed

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientesActionPerformed

    private void CadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastroClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroud;
    private javax.swing.JMenuItem CadastroCliente;
    private javax.swing.JMenuItem CadastroCorretor;
    private javax.swing.JMenuItem CadastroImovel;
    private javax.swing.JMenuItem CadastroSeguro;
    private javax.swing.JMenu Cadastros;
    private javax.swing.JMenuItem Clientes;
    private javax.swing.JMenuItem Corretores;
    private javax.swing.JMenuItem Imoveis;
    private javax.swing.JMenu Informacoes;
    private javax.swing.JMenuItem OperacaoAluguel;
    private javax.swing.JMenuItem OperacaoVenda;
    private javax.swing.JMenu Operacoes;
    private javax.swing.JMenuItem Seguros;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
