/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author João Pedro
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        ClienteT = new javax.swing.JLabel();
        CorretorT = new javax.swing.JLabel();
        CodigoIT = new javax.swing.JLabel();
        DataVT = new javax.swing.JLabel();
        ValorTT = new javax.swing.JLabel();
        FormaPT = new javax.swing.JLabel();
        CartaoT = new javax.swing.JLabel();
        NomeT = new javax.swing.JLabel();
        BandeiraT = new javax.swing.JLabel();
        NumeroT = new javax.swing.JLabel();
        ClienteText = new javax.swing.JTextField();
        CorretorText = new javax.swing.JTextField();
        CodigoIText = new javax.swing.JTextField();
        DataVText = new javax.swing.JTextField();
        ValorTText = new javax.swing.JTextField();
        FormaPBox = new javax.swing.JComboBox<>();
        NomeText = new javax.swing.JTextField();
        BandeiraText = new javax.swing.JTextField();
        NumeroText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Sombra = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Venda");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        ClienteT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ClienteT.setForeground(new java.awt.Color(255, 255, 255));
        ClienteT.setText("Cliente:");
        getContentPane().add(ClienteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        CorretorT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CorretorT.setForeground(new java.awt.Color(255, 255, 255));
        CorretorT.setText("Corretor:");
        getContentPane().add(CorretorT, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        CodigoIT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CodigoIT.setForeground(new java.awt.Color(255, 255, 255));
        CodigoIT.setText("Código do Imóvel:");
        getContentPane().add(CodigoIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        DataVT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DataVT.setForeground(new java.awt.Color(255, 255, 255));
        DataVT.setText("Data da Venda:");
        getContentPane().add(DataVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        ValorTT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ValorTT.setForeground(new java.awt.Color(255, 255, 255));
        ValorTT.setText("Valor Total da Venda:");
        getContentPane().add(ValorTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        FormaPT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FormaPT.setForeground(new java.awt.Color(255, 255, 255));
        FormaPT.setText("Forma de pagamento:");
        getContentPane().add(FormaPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        CartaoT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CartaoT.setForeground(new java.awt.Color(102, 255, 204));
        CartaoT.setText("Cartão");
        getContentPane().add(CartaoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        NomeT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NomeT.setForeground(new java.awt.Color(255, 255, 255));
        NomeT.setText("Nome:");
        getContentPane().add(NomeT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        BandeiraT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BandeiraT.setForeground(new java.awt.Color(255, 255, 255));
        BandeiraT.setText("Bandeira:");
        getContentPane().add(BandeiraT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        NumeroT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NumeroT.setForeground(new java.awt.Color(255, 255, 255));
        NumeroT.setText("Número:");
        getContentPane().add(NumeroT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        ClienteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteTextActionPerformed(evt);
            }
        });
        getContentPane().add(ClienteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 230, 30));
        getContentPane().add(CorretorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 230, 30));

        CodigoIText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoITextActionPerformed(evt);
            }
        });
        getContentPane().add(CodigoIText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 120, 30));

        DataVText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataVTextActionPerformed(evt);
            }
        });
        getContentPane().add(DataVText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 150, 30));
        getContentPane().add(ValorTText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 120, 30));

        FormaPBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boleto", "Débito", "Crédito", "Dinheiro" }));
        getContentPane().add(FormaPBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 150, 30));
        getContentPane().add(NomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 220, 30));
        getContentPane().add(BandeiraText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 220, 30));
        getContentPane().add(NumeroText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 220, 30));

        jButton1.setBackground(new java.awt.Color(102, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Cadastrar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 140, 30));

        Sombra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(Sombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 710, 550));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/logo2.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -140, -1, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClienteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteTextActionPerformed

    private void DataVTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataVTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataVTextActionPerformed

    private void CodigoITextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoITextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoITextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BandeiraT;
    private javax.swing.JTextField BandeiraText;
    private javax.swing.JLabel CartaoT;
    private javax.swing.JLabel ClienteT;
    private javax.swing.JTextField ClienteText;
    private javax.swing.JLabel CodigoIT;
    private javax.swing.JTextField CodigoIText;
    private javax.swing.JLabel CorretorT;
    private javax.swing.JTextField CorretorText;
    private javax.swing.JLabel DataVT;
    private javax.swing.JTextField DataVText;
    private javax.swing.JComboBox<String> FormaPBox;
    private javax.swing.JLabel FormaPT;
    private javax.swing.JLabel NomeT;
    private javax.swing.JTextField NomeText;
    private javax.swing.JLabel NumeroT;
    private javax.swing.JTextField NumeroText;
    private javax.swing.JLabel Sombra;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel ValorTT;
    private javax.swing.JTextField ValorTText;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
